const tagListDB: myTag[] = [
  {id: 1, type: '-', iconName: 'shuiguo', text: '水果'},
  {id: 2, type: '-', iconName: 'shuidianmei', text: '水电'},
  {id: 3, type: '-', iconName: 'xinyongkahuankuan', text: '信用卡还款'},
  {id: 4, type: '-', iconName: 'fangzu', text: '房租'},
  {id: 5, type: '-', iconName: 'lifa2', text: '理发'},
  {id: 6, type: '-', iconName: 'huafei', text: '话费'},
  {id: 7, type: '-', iconName: 'fushi', text: '服饰'},
  {id: 8, type: '-', iconName: 'canyinye', text: '餐饮'},
  {id: 9, type: '-', iconName: 'yule', text: '娱乐'},
  {id: 10, type: '-', iconName: 'movie', text: '看电影'},
  {id: 11, type: '-', iconName: 'drink', text: '饮料'},
  {id: 12, type: '-', iconName: 'jiaotong', text: '交通'},
  {id: 13, type: '-', iconName: 'youxi', text: '游戏'},
  {id: 14, type: '-', iconName: 'vegetables', text: '买菜'},
  {id: 15, type: '-', iconName: 'jingdong', text: '京东购物'},
  {id: 16, type: '-', iconName: 'taobao', text: '淘宝购物'},
  {id: 17, type: '+', iconName: 'hongbao', text: '红包'},
  {id: 18, type: '+', iconName: 'gupiao', text: '股票'},
  {id: 19, type: '+', iconName: 'jijin', text: '基金'},
  {id: 20, type: '+', iconName: 'jianzhi', text: '兼职'},
  {id: 21, type: '+', iconName: 'tuikuan', text: '退款'},
];
export default tagListDB;